package com.myspace.ccd_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AdditionalInformation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "AnswerValue")
	private java.lang.String answerValue;
	@org.kie.api.definition.type.Label(value = "QuestionId")
	private java.lang.Integer questionId;
	@org.kie.api.definition.type.Label(value = "QuestionPrompt")
	private java.lang.String questionPromt;
	@org.kie.api.definition.type.Label(value = "QuestionType")
	private java.lang.String questionType;

	public AdditionalInformation() {
	}

	public java.lang.String getAnswerValue() {
		return this.answerValue;
	}

	public void setAnswerValue(java.lang.String answerValue) {
		this.answerValue = answerValue;
	}

	public java.lang.Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(java.lang.Integer questionId) {
		this.questionId = questionId;
	}

	public java.lang.String getQuestionPromt() {
		return this.questionPromt;
	}

	public void setQuestionPromt(java.lang.String questionPromt) {
		this.questionPromt = questionPromt;
	}

	public java.lang.String getQuestionType() {
		return this.questionType;
	}

	public void setQuestionType(java.lang.String questionType) {
		this.questionType = questionType;
	}

	public AdditionalInformation(java.lang.String answerValue,
			java.lang.Integer questionId, java.lang.String questionPromt,
			java.lang.String questionType) {
		this.answerValue = answerValue;
		this.questionId = questionId;
		this.questionPromt = questionPromt;
		this.questionType = questionType;
	}

}